# Generated by Django 6.0.4 on 2026-04-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.job'),
        ),
    ]
